version: '3.8'

services:
  # ClickHouse Keeper Services
  keeper-1:
    image: clickhouse/clickhouse-keeper:latest-alpine
    ports:
      - "9181:9181"
      - "9234:9234"
      - "3888:3888"
    volumes:
      - ../config/keeper/templates:/etc/clickhouse-keeper/templates:ro
      - ../config/keeper/entrypoint.sh:/entrypoint.sh:ro
      - ../secrets/ssl/local:/etc/ssl/clickhouse:ro
      - ../secrets/passwords/local:/etc/secrets:ro
      - keeper-1-data:/var/lib/clickhouse-keeper
      - keeper-1-logs:/var/log/clickhouse-keeper
    env_file:
      - ../env/.env.clickhouse1
    entrypoint: ["/entrypoint.sh"]
    networks:
      - shared-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.keeper-node == true
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

  keeper-2:
    image: clickhouse/clickhouse-keeper:latest-alpine
    ports:
      - "9182:9181"
      - "9235:9234"
      - "3889:3888"
    volumes:
      - ../config/keeper/templates:/etc/clickhouse-keeper/templates:ro
      - ../config/keeper/entrypoint.sh:/entrypoint.sh:ro
      - ../secrets/ssl/local:/etc/ssl/clickhouse:ro
      - ../secrets/passwords/local:/etc/secrets:ro
      - keeper-2-data:/var/lib/clickhouse-keeper
      - keeper-2-logs:/var/log/clickhouse-keeper
    env_file:
      - ../env/.env.clickhouse2
    entrypoint: ["/entrypoint.sh"]
    networks:
      - shared-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.keeper-node == true
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

  keeper-3:
    image: clickhouse/clickhouse-keeper:latest-alpine
    ports:
      - "9183:9181"
      - "9236:9234"
      - "3890:3888"
    volumes:
      - ../config/keeper/templates:/etc/clickhouse-keeper/templates:ro
      - ../config/keeper/entrypoint.sh:/entrypoint.sh:ro
      - ../secrets/ssl/local:/etc/ssl/clickhouse:ro
      - ../secrets/passwords/local:/etc/secrets:ro
      - keeper-3-data:/var/lib/clickhouse-keeper
      - keeper-3-logs:/var/log/clickhouse-keeper
    env_file:
      - ../env/.env.clickhouse3
    entrypoint: ["/entrypoint.sh"]
    networks:
      - shared-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.keeper-node == true
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

networks:
  shared-network:
    external: true

volumes:
  keeper-1-data:
  keeper-2-data:
  keeper-3-data:
  keeper-1-logs:
  keeper-2-logs:
  keeper-3-logs: