version: '3.8'

services:
  # ClickHouse Server Services
  clickhouse-1:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse-1
    user: "clickhouse:clickhouse"
    ports:
      - "9001:9001"  # HTTPS port (backward compatible)
      - "9002:9002"  # TCP Secure port
      - "9440:9440"  # TCP Secure alternative
    volumes:
      - ../config/clickhouse/entrypoint.sh:/entrypoint.sh:ro
      - ../config/clickhouse/config-templates:/etc/clickhouse-server/config-templates:ro
      - ../config/clickhouse/user-templates:/etc/clickhouse-server/user-templates:ro
      - ../config/clickhouse/local/client-config.xml:/etc/clickhouse-client/config.xml:ro
      - ../secrets/ssl/local:/etc/ssl/clickhouse:ro
      - ../secrets/passwords/local:/etc/secrets:ro
      - clickhouse-1-data:/var/lib/clickhouse
      - clickhouse-1-logs:/var/log/clickhouse-server
    env_file:
      - ../env/.env.clickhouse1
    entrypoint: ["/entrypoint.sh"]
    networks:
      - shared-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.clickhouse-node == true
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3

  clickhouse-2:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse-2
    user: "clickhouse:clickhouse"
    ports:
      - "9011:9001"  # HTTPS port (different host port)
      - "9012:9002"  # TCP Secure port  
      - "9441:9440"  # TCP Secure alternative
    volumes:
      - ../config/clickhouse/entrypoint.sh:/entrypoint.sh:ro
      - ../config/clickhouse/config-templates:/etc/clickhouse-server/config-templates:ro
      - ../config/clickhouse/user-templates:/etc/clickhouse-server/user-templates:ro
      - ../config/clickhouse/local/client-config.xml:/etc/clickhouse-client/config.xml:ro 
      - ../secrets/ssl/local:/etc/ssl/clickhouse:ro
      - ../secrets/passwords/local:/etc/secrets:ro
      - clickhouse-2-data:/var/lib/clickhouse
      - clickhouse-2-logs:/var/log/clickhouse-server
    env_file:
      - ../env/.env.clickhouse2
    entrypoint: ["/entrypoint.sh"]
    networks:
      - shared-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.clickhouse-node == true
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3

  clickhouse-3:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse-3
    user: "clickhouse:clickhouse"
    ports:
      - "9021:9001"  # HTTPS port (different host port)
      - "9022:9002"  # TCP Secure port
      - "9442:9440"  # TCP Secure alternative
    volumes:
      - ../config/clickhouse/entrypoint.sh:/entrypoint.sh:ro
      - ../config/clickhouse/config-templates:/etc/clickhouse-server/config-templates:ro
      - ../config/clickhouse/user-templates:/etc/clickhouse-server/user-templates:ro
      - ../config/clickhouse/local/client-config.xml:/etc/clickhouse-client/config.xml:ro
      - ../secrets/ssl/local:/etc/ssl/clickhouse:ro
      - ../secrets/passwords/local:/etc/secrets:ro
      - clickhouse-3-data:/var/lib/clickhouse
      - clickhouse-3-logs:/var/log/clickhouse-server
    env_file:
      - ../env/.env.clickhouse3
    entrypoint: ["/entrypoint.sh"]
    networks:
      - shared-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.clickhouse-node == true
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3

networks:
  shared-network:
    external: true

volumes:
  clickhouse-1-data:
  clickhouse-2-data:
  clickhouse-3-data:
  clickhouse-1-logs:
  clickhouse-2-logs:
  clickhouse-3-logs:
